In [2]:
import numpy as np

# making N-d array

In [17]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [18]:
type(arr1)

numpy.ndarray

In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
type(arr3)

numpy.ndarray

In [23]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
type(arr4)

numpy.ndarray

In [25]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
type(arr5)

numpy.ndarray

In [27]:
arr6 = np.linspace(10,20,10)
arr6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
type(arr6)

numpy.ndarray

In [28]:
arr7 = arr6.copy()
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr8 = np.arange(10,20,2)
arr8

array([10, 12, 14, 16, 18])

# attributies and proporties

In [48]:
arr1

array([1, 2, 3, 4, 5])

In [30]:
arr1.shape

(5,)

In [49]:
arr1.ndim

1

In [52]:
arr1.size

5

In [53]:
arr1.itemsize

4

In [54]:
arr1.dtype

dtype('int32')

In [55]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2.shape

(2, 3)

In [56]:
arr2.ndim

2

In [57]:
arr2.size

6

In [58]:
arr2.itemsize

4

In [59]:
arr2.dtype

dtype('int32')

In [34]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr3.shape

(2, 3)

In [60]:
arr3.ndim

2

In [61]:
arr3.size

6

In [62]:
arr3.itemsize

8

In [63]:
arr3.dtype

dtype('float64')

In [64]:
arr3.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
arr4.shape

(3, 3)

In [37]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr5.shape

(5, 5)

In [39]:
arr6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [40]:
arr6.shape

(10,)

In [41]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [43]:
arr7.shape

(10,)

In [44]:
arr8

array([10, 12, 14, 16, 18])

In [45]:
arr8.shape

(5,)

In [66]:
arr9 = np.array([[[1,2],[4,5]],[[7,8],[9,10]]])
arr9

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10]]])

In [67]:
arr9.shape

(2, 2, 2)

In [65]:
arr9.ndim

3

# difference between list and array

In [68]:
lista = range(100)
arr11 = np.arange(100)

In [69]:
import sys

In [70]:
print(sys.getsizeof(87)*len(lista))

2800


# proof array used less memory than list

In [71]:
print(arr11.itemsize*arr11.size)

400
