In [1]:
import numpy as np

In [2]:
a = np.arange(3).reshape(1,3)
a

array([[0, 1, 2]])

In [3]:
b= np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
d = np.ar

In [2]:
a1 = np.arange(3).reshape(1,3)
a1

array([[0, 1, 2]])

In [3]:
a2 = np.arange(3).reshape(3,1)
a2

array([[0],
       [1],
       [2]])

In [4]:
a1+a2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [5]:
a2= np.arange(4)
a3= np.arange(20).reshape(5,4)
a2+a3

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])