In [1]:
import numpy as np

In [2]:
arr= np.random.randint(low=1,high=100,size=20)

In [3]:
arr

array([89, 54, 13, 54, 53, 59, 52, 31,  9, 37,  8, 95,  3, 93, 36, 87, 37,
       49, 17, 74])

In [4]:
arr>50

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True, False,  True, False,  True, False, False,
       False,  True])

In [5]:
arr[arr>50]

array([89, 54, 54, 53, 59, 52, 95, 93, 87, 74])

In [6]:
arr[(arr>50)&(arr%2!=0)]

array([89, 53, 59, 95, 93, 87])

In [7]:
arr[(arr>50)&(arr%2!=0)]=0

In [8]:
arr

array([ 0, 54, 13, 54,  0,  0, 52, 31,  9, 37,  8,  0,  3,  0, 36,  0, 37,
       49, 17, 74])