In [7]:
import numpy as np

In [8]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# inde

In [13]:
arr1[5]
arr1[2]
arr1[3]
arr1[0]

array([0, 1, 2, 3])

# sli

In [ ]:
arr1[2:3]


array([[ 8,  9, 10, 11]])

In [15]:
arr1[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [18]:
arr1[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [20]:
arr1[4:,0:2]

array([[16, 17],
       [20, 21]])

# iteration

In [22]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [23]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
