In [17]:
import numpy as np

In [18]:
np.random.random()

0.1862602113776709

In [19]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [20]:
np.random.uniform(1,10)

7.482920440979423

# uniform float and demial

In [21]:
np.random.uniform(10,20,5)

array([10.00114375, 13.02332573, 11.46755891, 10.92338595, 11.86260211])

# integer 

In [29]:
np.random.randint(1,10)

6

In [32]:
np.random.randint(10,15,4)

array([11, 11, 10, 11])

In [42]:
np.random.seed(8)
a = np.random.randint(5,15,8)
a

array([ 8,  9,  6, 14, 10, 13,  8, 13])

In [43]:
np.min(a)

6

In [44]:
np.max(a)

14

In [45]:
np.argmin(a)

2

In [47]:
a[np.argmin(a)]

6

In [48]:
a[np.argmax(a)]

14

In [69]:
b= np.random.randint(1,50,10)
b

array([ 3, 19, 39, 23, 40, 47, 42,  7, 32, 33])

In [72]:
 d = np.where(b%2==1,-1,b)

In [73]:
d

array([-1, -1, -1, -1, 40, -1, 42, -1, 32, -1])

In [74]:
b

array([ 3, 19, 39, 23, 40, 47, 42,  7, 32, 33])

In [76]:
f= np.random.randint(1,100,20)

In [77]:
f

array([29,  6, 67, 20, 76, 12, 47, 93, 73, 56, 90, 15, 40, 16, 20, 59, 44,
       16, 29, 33])

In [79]:
h = np.sort(f)
h

array([ 6, 12, 15, 16, 16, 20, 20, 29, 29, 33, 40, 44, 47, 56, 59, 67, 73,
       76, 90, 93])

In [81]:
np.percentile(f,25)

19.0

In [82]:
np.percentile(f,100)

93.0

In [83]:
np.percentile(f,98.8)

92.316