In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])

In [3]:
arr1+arr2

array([ 5,  7,  9, 11])

In [4]:
arr1-arr2

array([-3, -3, -3, -3])

In [5]:
arr1*arr2

array([ 4, 10, 18, 28])

In [6]:
arr2 >3

array([ True,  True,  True,  True])

In [7]:
arr1%arr2

array([1, 2, 3, 4])

In [8]:
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [10]:
arr1.min()

1

In [11]:
arr1.max()

4

In [14]:
arr= np.array([[6,7],[8,9],[10,11]])
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
arr.min(axis=0)

array([6, 7])

# proof olumnwise kon sy min ha 

In [16]:
arr.min(axis=1)

array([ 6,  8, 10])

# proof rowwise sy kon sy min ha

In [17]:
arr.sum()

51

In [18]:
arr.sum(axis=0)

array([24, 27])

In [20]:
arr.sum(axis=1)

array([13, 17, 21])

In [21]:
np.mean(arr1)

2.5

In [22]:
np.median(arr2)

5.5

In [23]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
arr4 = np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [33]:
np.exp(arr)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [34]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
arr.ndim

2

# this change col to row 

In [36]:
arr.ravel()

array([ 6,  7,  8,  9, 10, 11])

# transpose 

In [38]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
arr.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

# hstack

In [42]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [43]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [48]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [49]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]